sudo: false
language: node_js
cache:
  directories:
    - node_modules
services:
  - couchdb
before_script:
  - curl -X PUT localhost:5984/users_wkoa_test
node_js:
  - "4.3.1"
  - "5"
  - "6"
  - "7"
